<template>
  <div class="service-hall">
    <!-- 顶部搜索区 -->
    <div class="header-section">
      <div class="title-area">
        <h2>办事大厅</h2>
        <p class="subtitle">一站式教务服务平台</p>
      </div>
      <div class="search-area">
        <el-input
          v-model="searchKeyword"
          placeholder="搜索办事项目..."
          class="search-input"
          :prefix-icon="Search"
          clearable
        />
        <el-button type="primary" @click="handleMyApplications">我的申请</el-button>
      </div>
    </div>

    <!-- 分类导航 -->
    <div class="category-nav">
      <div
        v-for="cat in categories"
        :key="cat.key"
        class="category-item"
        :class="{ active: currentCategory === cat.key }"
        @click="currentCategory = cat.key"
      >
        <el-icon class="cat-icon"><component :is="cat.icon" /></el-icon>
        <span>{{ cat.label }}</span>
      </div>
    </div>

    <!-- 快捷入口 -->
    <div class="quick-links" v-if="displayQuickLinks.length">
      <div 
        v-for="link in displayQuickLinks" 
        :key="link.id" 
        class="quick-link-card" 
        @click="router.push(link.route)"
      >
        <el-icon class="quick-icon" :style="{ background: link.icon_bg, color: link.icon_color }">
          <component :is="link.icon" />
        </el-icon>
        <div class="quick-info">
          <h4>{{ link.name }}</h4>
          <p>{{ link.description }}</p>
        </div>
      </div>
    </div>

    <!-- 办事项目列表 -->
    <div class="service-list">
      <el-row :gutter="20">
        <el-col
          v-for="item in filteredServices"
          :key="item.id"
          :xs="24"
          :sm="12"
          :md="8"
          :lg="6"
        >
          <div class="service-card" @click="handleServiceClick(item)">
            <div class="card-icon">
              <el-icon><component :is="item.icon || 'Document'" /></el-icon>
            </div>
            <div class="card-content">
              <h3>{{ item.name }}</h3>
              <div class="tags">
                <el-tag size="small" effect="plain">{{ getCategoryLabel(item.category) }}</el-tag>
                <el-tag size="small" type="info" effect="plain">{{ item.processing_time }}</el-tag>
              </div>
              <div class="status-indicator" :class="item.status">
                <span class="dot"></span>
                {{ item.status === 'available' ? '可办理' : '暂停办理' }}
              </div>
            </div>
          </div>
        </el-col>
      </el-row>
      
      <el-empty v-if="filteredServices.length === 0" description="暂无相关办事项目" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { Search } from '@element-plus/icons-vue'
import axios from 'axios'
import { ElMessage } from 'element-plus'

const router = useRouter()
const searchKeyword = ref('')
const currentCategory = ref('all')
const services = ref<any[]>([])
const quickLinks = ref<any[]>([])
// 过滤占位/自动生成的快捷入口（避免前端展示英文占位项）
const displayQuickLinks = computed(() => {
  const list = Array.isArray(quickLinks.value) ? quickLinks.value : []
  return list.filter((l: any) => {
    const nameRaw = String(l?.name || '').trim()
    const descRaw = String(l?.description || '').trim()
    const name = nameRaw.toLowerCase()
    const desc = descRaw.toLowerCase()
    const isPlaceholder =
      /^resource\b/.test(name) ||
      /^resource\d+/.test(name) ||
      /^资源\b/.test(nameRaw) ||
      desc.includes('auto-generated') ||
      desc.includes('autogenerated') ||
      desc.includes('auto generated')
    return !isPlaceholder
  })
})

const categories = [
  { key: 'all', label: '全部服务', icon: 'More' },
  { key: '学籍管理', label: '学籍管理', icon: 'User' },
  { key: '课程管理', label: '课程管理', icon: 'Reading' },
  { key: '成绩管理', label: '成绩管理', icon: 'DataLine' },
  { key: '证书办理', label: '证书办理', icon: 'Document' },
  { key: '其他服务', label: '其他服务', icon: 'School' }
]

const getCategoryLabel = (key: string) => {
  const cat = categories.find(c => c.key === key)
  return cat ? cat.label : key
}

const filteredServices = computed(() => {
  return services.value.filter(item => {
    const matchCategory = currentCategory.value === 'all' || item.category === currentCategory.value
    const matchKeyword = !searchKeyword.value || item.name.includes(searchKeyword.value)
    return matchCategory && matchKeyword
  })
})

const fetchQuickLinks = async () => {
  try {
    const response = await axios.get('/quick-link/list', {
      headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }
    })
    quickLinks.value = Array.isArray(response.data) ? response.data : []
  } catch (error) {
    console.error('获取快捷入口失败', error)
    quickLinks.value = []
  }
}

const fetchServices = async () => {
  try {
    const token = localStorage.getItem('token')
    console.log('Current Token:', token)
    if (!token) {
      ElMessage.warning('未检测到登录凭证，请重新登录')
      return
    }
    const response = await axios.get('/service/list')
    services.value = response.data
  } catch (error) {
    console.error('获取办事项目失败', error)
    ElMessage.error('获取办事项目失败')
  }
}

const handleServiceClick = (item: any) => {
  router.push(`/service/detail/${item.id}`)
}

const handleMyApplications = () => {
  router.push('/service/my-applications')
}

onMounted(() => {
  fetchServices()
  fetchQuickLinks()
})
</script>

<style scoped>
.service-hall {
  padding: 20px;
  max-width: 1200px;
  margin: 0 auto;
}

.header-section {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 30px;
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  padding: 20px;
  border-radius: 12px;
  border: 1px solid var(--border-color);
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
  flex-wrap: wrap;
  gap: 14px;
}

.title-area h2 {
  margin: 0;
  font-size: 24px;
  color: var(--el-text-color-primary);
}

.subtitle {
  margin: 5px 0 0;
  color: var(--el-text-color-secondary);
  font-size: 14px;
}

.search-area {
  display: flex;
  gap: 15px;
  align-items: center;
  flex-wrap: wrap;
}

.search-input {
  width: 300px;
}

.category-nav {
  display: flex;
  gap: 15px;
  margin-bottom: 20px;
  overflow-x: auto;
  padding-bottom: 10px;
}

.quick-links {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 20px;
  margin-bottom: 30px;
}

@media (max-width: 1200px) {
  .quick-links {
    grid-template-columns: repeat(3, 1fr);
  }
}

@media (max-width: 768px) {
  .quick-links {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 480px) {
  .quick-links {
    grid-template-columns: 1fr;
  }
}

.quick-link-card {
  display: flex;
  align-items: flex-start;
  gap: 15px;
  padding: 20px;
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.3s;
  border: 1px solid var(--border-color);
  min-height: 110px;
}

.quick-link-card:hover {
  transform: translateY(-2px);
  box-shadow: var(--el-box-shadow);
  border-color: var(--el-color-primary-light-7);
}

.quick-icon {
  width: 48px;
  height: 48px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 24px;
  flex-shrink: 0;
}

.quick-info {
  flex: 1;
}

.quick-info h4 {
  margin: 0 0 8px;
  font-size: 16px;
  color: var(--el-text-color-primary);
}

.quick-info p {
  margin: 0;
  font-size: 13px;
  color: var(--el-text-color-secondary);
}

.category-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 20px;
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  border-radius: 20px;
  cursor: pointer;
  transition: all 0.3s;
  border: 1px solid var(--border-color);
  white-space: nowrap;
}

.category-item:hover {
  color: #000 !important;
  border-color: var(--el-color-primary-light-7);
  background: var(--el-color-primary-light-9);
}

.category-item.active {
  background: var(--el-color-primary);
  color: var(--el-color-white);
  border-color: var(--el-color-primary);
  box-shadow: var(--el-box-shadow-light);
}

.service-card {
  background: var(--card-bg);
  backdrop-filter: blur(10px);
  border-radius: 12px;
  padding: 20px;
  margin-bottom: 20px;
  cursor: pointer;
  transition: all 0.3s;
  border: 1px solid var(--border-color);
  display: flex;
  align-items: flex-start;
  gap: 15px;
}

.service-card:hover {
  transform: translateY(-2px);
  box-shadow: var(--el-box-shadow);
  border-color: var(--el-color-primary-light-7);
}

.card-icon {
  width: 48px;
  height: 48px;
  background: var(--el-color-primary-light-9);
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--el-color-primary) !important;
  font-size: 24px;
  flex-shrink: 0;
}

.card-content {
  flex: 1;
  overflow: hidden;
}

.card-content h3 {
  margin: 0 0 10px;
  font-size: 16px;
  color: var(--el-text-color-primary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.tags {
  display: flex;
  gap: 5px;
  margin-bottom: 10px;
  flex-wrap: wrap;
}

/* Removed conflicting tag styles to let global theme handle it */

.status-indicator {
  font-size: 12px;
  display: flex;
  align-items: center;
  gap: 5px;
}

.status-indicator.available {
  color: var(--el-color-success);
}

.status-indicator.paused {
  color: var(--el-text-color-secondary);
}

.dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: currentColor;
}
</style>
